config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/sign_in', to: 'sessions#sign_in', as: 'sign_in'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#sign_out', as: 'sign_out'
  delete '/sign_out', to: 'sessions#destroy'

  resources :users, only: [:new, :create]

namespace :api do
    resources :schools do
      resources :teachers
      resources :students
    end
end
resources :schools do
  resources :teachers
  resources :students
end
  root 'schools#index'

end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, presence: true
  has_many :teacher, dependent: :destroy
  has_many :student, dependent: :destroy
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, presence: true
  validates :teacher_id, presence: true
  belongs_to :school, counter_cache: true
  belongs_to :teacher, counter_cache: true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :school, counter_cache: true
  has_many :student, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  has_secure_password
end

app/controllers/api/schools_controller.rb
class Api::SchoolsController < ApplicationController
  def index
    render json: School.all
  end

  def show
  #   render json: Post.find(params.fetch(:id))
  #                    .to_json(methods: [:prev, :next],
  #                             except: :user_id,
  #                             include: {
  #                               comments: {
  #                                 except: :user_id
  #                               }
  #                             })
  # rescue ActiveRecord::RecordNotFound
  #   render json: { message: "Not found", status: 404 }, status: 404
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user

  def signed_in?
    session[:user_id].present?
  end

  helper_method :signed_in?

  def current_user
    return if session[:user_id].nil?
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user

  def authenticate_user
    if session[:user_id].nil?
      flash[:alert] = "Must be signed in"
      redirect_to sign_in_path
    end
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
skip_before_action :authenticate_user, only: [:index]

  def index
    @schools = School.page params[:page]
  end

  def show
    @school = get_school
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to @school
    else
      render :new
    end
  end

  def edit
    @school = get_school
  end

  def update
    @school = get_school

    if @school.update(school_params)
      redirect_to @school
    else
      render :edit
    end
  end

  def destroy
    @school = get_school

    if @school.destroy
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  private
  def get_school
    School.find(params.fetch(:id))
  end

  def school_params
    params.require(:school).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user


  def sign_in
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You have signed in."
      redirect_to root_path
    else
      flash.now[:alert] = "No records match that Username and Password combination."
      render :sign_in
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed out"
    redirect_to root_path
  end

  def sign_out
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.where(school: params[:school_id]).page params[:page]
  end

  def show
    @student = get_student
  end

  def new
    @student = Student.new
    @school = School.find(params.fetch(:school_id))
  end

  def create
    @student = Student.new(student_params)
    @school = School.find(params.fetch(:school_id))

    if @student.save
      redirect_to school_student_path(@school, @student)
    else
      render :new
    end
  end

  def edit
    @student = get_student
    @school = School.find(params.fetch(:school_id))

  end

  def update
    @student = get_student
    @school = School.find(params.fetch(:school_id))

    if @student.update(student_params)
      redirect_to school_student_path(@school, @student)
    else
      render :edit
    end
  end

  def destroy
    @student = get_student
    school = @student.school

    if @student.destroy
      redirect_to school_path(school)
    else
      redirect_to :back
    end
  end

  private
  def get_student
    Student.find(params.fetch(:id))
  end

  def student_params
    params.require(:student).permit(:name, :school_id, :teacher_id)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.where(school: params[:school_id]).page params[:page]
  end

  def show
    @teacher = get_teacher
    @students = @teacher.student.page params[:page]
  end

  def new
    @teacher = Teacher.new
    @school = School.find(params.fetch(:school_id))
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @school = School.find(params.fetch(:school_id))

    if @teacher.save
      redirect_to school_teacher_path(@school, @teacher)
    else
      render :new
    end
  end

  def edit
    @teacher = get_teacher
    @school = School.find(params.fetch(:school_id))

  end

  def update
    @teacher = get_teacher
    @school = School.find(params.fetch(:school_id))

    if @teacher.update(teacher_params)
      redirect_to school_teacher_path(@school, @teacher)
    else
      render :edit
    end
  end

  def destroy
    @teacher = get_teacher
    school = @teacher.school

    if @teacher.destroy
      redirect_to school_path(school)
    else
      redirect_to :back
    end
  end


  private
  def get_teacher
    Teacher.find(params.fetch(:id))
  end

  def teacher_params
    params.require(:teacher).permit(:name, :school_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account created.  Signing in and returning to directory."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:notice] = "Failed to make account."
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
  #TODO: add auth lockouts skip_before_action :authenticate_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account created.  Signing in and returning to directory."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schoolapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class='navbar navbar-default'>
  <ul class="nav navbar-nav navbar">
    <li><%= link_to "Return to Directory", schools_path, class: "btn btn-info" %></li>
    <% unless signed_in? %>
      <li> <%= link_to "Sign In", sign_in_path, class: "btn btn-success" %> </li>
      <li> <%= link_to "Sign Up", new_user_path, class: "btn btn-warning" %> </li>
    <% else %>
      <li> <%= link_to "Sign Out", sign_out_path, method: :DELETE, class: "btn btn-danger" %> </li>
    <% end %>
  </ul>
</nav>

<div class='container'>
  <%= flash[:notice] %>
  <%= flash[:alert] %>

  <%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/schools/edit.html.erb
<div class='col-md-offset-2 col-md-6'>
  <%= form_for(@school, class: 'form') do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class='row'>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/schools/index.html.erb
<h1>Registered Schools</h1>
<div id = "clicker">
  Brew Some Java
</div>
<% if signed_in? %>
  <%= link_to "Register a New Campus", new_school_url, class: 'btn btn-default btn-compliment' %>
<% end %>
<hr>
<% @schools.each do |school| %>
  <div class='col-md-offset-2 col-md-6 target'>
    <%= link_to school.name, school, class: 'btn btn-default btn-main' %>
  </div>
<% end %>
<div class = "col-md-offset-2 col-md-6">
<%= paginate @schools %>
</div>

app/views/schools/new.html.erb
<h1>Add a new School to District</h1>
<hr />
<div class='col-md-offset-2 col-md-6'>
  <%= form_for(@school, class: 'form') do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class='row'>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/schools/show.html.erb
<h1> Campus Details </h2>
<div class= "col-md-offset-2 col-md-6">
  <%= @school.name%> || <%= link_to "Edit School", edit_school_path(@school), class: 'btn btn-default' %>
  <hr>
  <%= link_to "Purge Campus Records", school_path(@school), method: :DELETE, data: { confirm: "Confirm Campus Purge(All Teachers and Students included)?" }, class: 'btn btn-danger' %>
  <hr>
  <%= link_to "New Teacher", new_school_teacher_path(@school), class: 'btn btn-default' %>
  <%= link_to "New Student", new_school_student_path(@school), class: 'btn btn-default' %>
  <hr>
  <% unless @school.teacher.first.nil? %>
    <%= link_to "Teachers", school_teachers_path(@school), class: 'btn btn-default' %>: <%=@school.teacher.count%>  |
  <% end %>
  <% unless @school.student.first.nil? %>
    <%= link_to "Students", school_students_path(@school), class: 'btn btn-default' %>:  <%=@school.student.count%>
  <% end %>
</div>

app/views/students/edit.html.erb
<h1>Editing a Student</h1>
<h2> Current School: <%=@school.name%> </h2>
<hr />
<div class='col-md-offset-2 col-md-6'>
  <%= form_for([@school, @student], class: 'form') do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.hidden_field :school_id, :value => @school.id %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :teacher_id %>
        <%= f.collection_select :teacher_id, @school.teacher ,:id,:name, include_blank: true %>
      </div>
    </div>
    <div class='row'>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/students/index.html.erb
<h1>Enrolled Students</h1>
<%= link_to "To Current School", school_url(@students.first.school.id), class: 'btn btn-default' %>
<hr>
<h2> Current Location: <%=@students.first.school.name%></h2>
<hr>
<% @students.each do |student| %>
  <div class='col-md-offset-2 col-md-6'>
    <%= link_to student.name, school_student_path(student.school.id, student.id), class: 'btn btn-default' %>
  </div>
<% end %>
<div class = "col-md-offset-2 col-md-6">
<%= paginate @students %>
</div>

app/views/students/new.html.erb
<h1>Add a New Student</h1>
<h2> Current School: <%=@school.name%> </h2>
<hr />
<div class='col-md-offset-2 col-md-6'>
  <%= form_for([@school, @student], class: 'form') do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.hidden_field :school_id, :value => @school.id %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :teacher_id %>
        <%= f.collection_select :teacher_id, @school.teacher ,:id,:name, include_blank: true %>
      </div>
    </div>
    <div class='row'>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/students/show.html.erb
<h1>Viewing Student Record</h1>
<%= link_to "To Current School", school_url(@student.school.id), class: 'btn btn-default' %>
<hr>
<h2> <%=@student.name%></h2>
<%= link_to "Edit Student", edit_school_student_path(@student.school.id, @student), class: 'btn btn-default' %>
<hr>
<%= link_to "Delete Student Record", school_student_path(@student.school.id, @student), method: :DELETE, data: { confirm: "Confirm Student Deletion?" }, class: 'btn btn-danger' %>
<hr>
Studying under: <%=@student.teacher.name%>

app/views/teachers/edit.html.erb
<h1>Editing a Teacher Record</h1>
<h2> Current School: <%=@school.name%> </h2>
<hr />
<div class='col-md-offset-2 col-md-6'>
  <%= form_for([@school, @teacher], class: 'form') do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.hidden_field :school_id, :value => @school.id %>
      </div>
    </div>
    <div class='row'>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/teachers/index.html.erb
<h1>Teachers on Staff</h1>
<%= link_to "To Current School", school_url(@teachers.first.school.id), class: 'btn btn-default' %>
<hr>
<h2> Current Location: <%=@teachers.first.school.name%></h2>
<hr>
<% @teachers.each do |teacher| %>
  <div class='col-md-offset-2 col-md-6'>
    <%= link_to teacher.name, school_teacher_path(teacher.school.id, teacher.id), class: 'btn btn-default' %>
  </div>
<% end %>
<div class = "col-md-offset-2 col-md-6">
<%= paginate @teachers %>
</div>

app/views/teachers/new.html.erb
<h1>Teachers#new</h1>
<p>Find me in app/views/teachers/new.html.erb</p>
<hr />
<div class='col-md-offset-2 col-md-6'>
  <%= form_for([@school, @teacher], class: 'form') do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.hidden_field :school_id, :value => @school.id %>
      </div>
    </div>
    <div class='row'>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/teachers/show.html.erb
<h1>Teacher Record</h1>
<%= link_to "To Current School", school_url(@teacher.school.id), class: 'btn btn-default' %>
<hr>
<h2><%=@teacher.name%></h2>
<%= link_to "Edit Teacher", edit_school_teacher_path(@teacher.school.id, @teacher), class: 'btn btn-default' %>
<hr>
<%= link_to "Delete Teacher Record", school_teacher_path(@teacher.school.id, @teacher), method: :DELETE, data: { confirm: "Confirm Teacher Deletion?" }, class: 'btn btn-danger' %>
<hr>
Current Students:<br>
<% @students.each do |student| %>
  <div class='col-md-offset-2 col-md-6'>
    <%= link_to student.name, school_student_path(student.school.id, student.id), class: 'btn btn-default' %>
  </div>
<% end %>
<div class = "col-md-offset-2 col-md-6">
<%= paginate @students %>
</div>

app/views/users/new.html.erb
<h1>Creating a new account</h1>

<%= form_for(@user) do |f| %>
  <div class='row'>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class='row'>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class='row'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class='row'>
    <%= f.submit %>
  </div>
<% end %>